let S=[],cur=null,favs=JSON.parse(localStorage.getItem('favs')||'[]'),fs=+(localStorage.getItem('fs')||19);const $=x=>document.getElementById(x);
fetch('data/sermons.json').then(r=>r.json()).then(x=>{S=x;bind();render(S);font()});
function bind(){$('q').oninput=e=>{let q=e.target.value.toLowerCase();$('listTitle').textContent=q?'검색 결과':'설교 목록';render(S.filter(s=>(s.title+s.scripture+s.content.join(' ')).toLowerCase().includes(q)))};
$('today').onclick=()=>open(S[Math.floor(Math.random()*S.length)].id);$('fav').onclick=()=>{$('listTitle').textContent='즐겨찾기';render(S.filter(s=>favs.includes(s.id)))};$('all').onclick=()=>{$('q').value='';$('listTitle').textContent='설교 목록';render(S)};
$('back').onclick=()=>{$('detail').hidden=true;$('home').hidden=false};$('star').onclick=()=>{favs=favs.includes(cur)?favs.filter(x=>x!==cur):[...favs,cur];localStorage.setItem('favs',JSON.stringify(favs));star()};
$('minus').onclick=()=>setfs(fs-1);$('plus').onclick=()=>setfs(fs+1);$('reset').onclick=()=>setfs(19);$('prev').onclick=()=>nav(-1);$('next').onclick=()=>nav(1);$('dark').onclick=()=>document.body.classList.toggle('dark');
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js')}
function render(a){$('count').textContent=a.length+'편';$('list').innerHTML='';a.forEach(s=>{let b=document.createElement('button');b.className='item';b.innerHTML=`<span class=n>${s.number}</span><img src="${s.image}"><span><h3>${s.title}</h3><p>${s.scripture}</p></span><b>${favs.includes(s.id)?'★':''}</b>`;b.onclick=()=>open(s.id);$('list').appendChild(b)})}
function open(id){cur=id;let s=S.find(x=>x.id===id);$('hero').src=s.image;$('num').textContent='설교 '+s.number;$('title').textContent=s.title;$('verse').textContent=s.scripture;$('body').innerHTML=s.content.map(p=>`<p class="${/^(첫째|둘째|셋째|넷째)/.test(p)?'section':''}">${p}</p>`).join('');$('note').hidden=!s.editor_note;$('noteText').textContent=s.editor_note||'';star();$('home').hidden=true;$('detail').hidden=false;scrollTo(0,0)}
function star(){$('star').textContent=favs.includes(cur)?'★':'☆'}function setfs(n){fs=Math.max(15,Math.min(28,n));localStorage.setItem('fs',fs);font()}function font(){document.documentElement.style.setProperty('--fs',fs+'px')}function nav(d){let i=S.findIndex(s=>s.id===cur);if(S[i+d])open(S[i+d].id)}